language: python
python: 3.6
install:
- pip install .[dev]
script: 
- flake8
- pytest
deploy:
  provider: pypi
  user: elgehelge
  password:
    secure: DBVQRZ55OILaSJC5M5tI/G0Q+AJyxg7RhynkMbFhmx+uUaDRNVe2YRRUGJw+rNiSdI4BV690pDFrq8aN0S36wzpM3TSTOGY3/pfTuOn6E4N3fzz5JI+EOoJg7k6zkZIVPx2JJEd0SLJPlrCP14cxl4nk/c1Fd2b4xZkGQdZOo11fWy9oAr2z5su0eJIOw6XgxTRUgSUaC5Tz/6fYQKwsN0YmdBl7eE3t2eJXDYuQg6h/4xFvp7zL00I1y3FSE+h44cMlb6zlz7gODF7LlrH1Izdl0pvIAedzXW0C/hDsVmVmkFOXx1eDfRuXfkkuVcyCSShqHrhONf4VgsI/Z4XeZchhb3Yd+tfkZGE4qpEp+0OkyEypxFuz9+Nj6Mho16U4DSp2zkeWWg7W537W3zptuxYLwk6MqYtcfV/eqrc2Ri4KLNfA8kWapr5V71PlOjrR6ly2kOMwgKYsVCFMzvrBIUjtU9C8mKhqbkqLHG6Lh+SRDe7sJqdq3DumbHNTzXykUbvTOprv9d03idtr0M+DSQe52T2pSTArWRKLkpL6TdGLqq4ye651VBEFjzwtnQY/L/1gecqqBA3wfjNaUSM7jKLCcaJXqLU93WcJ2E3sHeGUj9BIyBNCxuVCzOKtT6msN0Q+NK1l8quBpEeh/BWSJZnKmhwKeXcw1RMGWq9Z5pg=
  on:
    tags: true
